# Generated by Django 4.2.2 on 2023-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=15, verbose_name='Precio'),
        ),
    ]
